### ISSUE TITLE
MoviePy couldn't find the codec associated with the filename

### ISSUE THREAD

**Issue by vinaykumarhs2020** [udacity/CarND-Behavioral-Cloning-P3#15]
```
$python video.py --fps 30 first_working/

Creating video first_working/.mp4, FPS=30
Traceback (most recent call last):
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/moviepy/video/VideoClip.py", line 276, in write_videofile
    codec = extensions_dict[ext]['codec'][0]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../video.py", line 27, in <module>
    main()
  File "../video.py", line 23, in main
    clip.write_videofile(video_file)
  File "<decorator-gen-51>", line 2, in write_videofile
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-50>", line 2, in write_videofile
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/moviepy/video/VideoClip.py", line 278, in write_videofile
    raise ValueError("MoviePy couldn't find the codec associated "
ValueError: MoviePy couldn't find the codec associated with the filename. Provide the 'codec' parameter in write_videofile.
```

**Comment by vinaykumarhs2020** [comment]
Changing [video.py-L20](https://github.com/udacity/CarND-Behavioral-Cloning-P3/blob/da5df48f4b14bb8aa98156879ce301c63f759096/video.py#L20)
from 
   ```
   video_file = args.image_folder + '.mp4'
   ```
 to 
   ```
   video_file = args.image_folder + 'output_video.mp4'
   ```
solves the issue

**Comment by r0busta** [comment]
Thanks for the solution!
