### ISSUE TITLE
python-socketio IndexError: too many indices for array message handler error

### ISSUE THREAD

**Issue by zhaoyingjun** [udacity/CarND-Behavioral-Cloning-P3#25]
('connect ', 'c15c52397cdb4e5eafa5da78993a3b66')
message handler error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/engineio/server.py", line 398, in _trigger_event
    return self.handlers[event](*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/socketio/server.py", line 520, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/socketio/server.py", line 456, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/socketio/server.py", line 459, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/socketio/server.py", line 488, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "drive.py", line 64, in telemetry
    steering_angle = float(model.predict(image_array[None, :, :, :], batch_size=1))
IndexError: too many indices for array
message handler error

please help me.

**Comment by baumanab** [comment]
Thank you for letting us know. It isn't clear that this is a bug. Would you mind discussing with a mentor? If it is a bug, let us know, and we can re-open the issue.

**Comment by zhaoyingjun** [comment]
OK I don't mind
