### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2

### ISSUE THREAD

**Issue by FutureKen** [udacity/CarND-Behavioral-Cloning-P3#27]
I tried to run drive.py with or without a model.h5 file, they all get the same error message here:

**UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence**

Looks like the issue occur when it try to import socketio. 

I already installed all the libs by following the guide here [CarND-Term1-Starter-Kit](https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md), the previous projects have no issue at all. 

I'm running at Windows 10, 64-bit Version 1709

Console log:
```
(carnd-term1) λ python drive.py
Traceback (most recent call last):
  File "drive.py", line 8, in <module>
    import socketio
  File "C:\Users\Kenneth\Miniconda3\envs\carnd-term1\lib\site-packages\socketio\__init__.py", line 8, in <module>
    from .zmq_manager import ZmqManager
  File "C:\Users\Kenneth\Miniconda3\envs\carnd-term1\lib\site-packages\socketio\zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "C:\Users\Kenneth\Miniconda3\envs\carnd-term1\lib\site-packages\eventlet\__init__.py", line 10, in <module>
    from eventlet import convenience
  File "C:\Users\Kenneth\Miniconda3\envs\carnd-term1\lib\site-packages\eventlet\convenience.py", line 6, in <module>
    from eventlet.green import socket
  File "C:\Users\Kenneth\Miniconda3\envs\carnd-term1\lib\site-packages\eventlet\green\socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "C:\Users\Kenneth\Miniconda3\envs\carnd-term1\lib\site-packages\eventlet\support\greendns.py", line 390, in <module>
    resolver = ResolverProxy(hosts_resolver=HostsResolver())
  File "C:\Users\Kenneth\Miniconda3\envs\carnd-term1\lib\site-packages\eventlet\support\greendns.py", line 171, in __init__
    self._load()
  File "C:\Users\Kenneth\Miniconda3\envs\carnd-term1\lib\site-packages\eventlet\support\greendns.py", line 198, in _load
    lines = self._readlines()
  File "C:\Users\Kenneth\Miniconda3\envs\carnd-term1\lib\site-packages\eventlet\support\greendns.py", line 184, in _readlines
    for line in fp:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
```

**Comment by FutureKen** [comment]
OK, I solved it by editing File "C:\Users\Kenneth\Miniconda3\envs\carnd-term1\lib\site-packages\eventlet\support\greendns.py", line 183, 

Replaced it with `with open(self.fname, 'rU', encoding='utf-8') as fp:`

Not sure why it used a gbk encoding which caused the error.

**Comment by baumanab** [comment]
Thanks for letting us know, and great job finding a solution!
